- name: Setup Fedora installation.
  hosts: localhost
  connection: local
  gather_facts: true
  vars:
    real_user: "{{ lookup('env', 'SUDO_USER') | default(ansible_user_id) }}"

  roles:
    - post-install 
    - ssh 
    - utilities 
    - fonts
    - dotfiles
    - hyprland
    - applications
    - development 
