- name: Setup Fedora installation.
  hosts: localhost
  connection: local
  gather_facts: true

  roles:
    - post-install 
    - utilities 
    - fonts
    - dotfiles
    - hyprland
    - applications
    - development 
