- name: Clone dotfiles repo if not already present.
  become: false
  ansible.builtin.git:
    repo: "https://github.com/JanCoe/dotfiles.git"
    dest: "/home/{{ real_user }}/.dotfiles"
    version: main
    update: no

- name: Ensure stow is installed.
  become: true
  ansible.builtin.dnf:
    name: stow
    state: present

- name: Delete dotfiles that will conflict.
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop:
    - "/home/{{ real_user }}/.bash_history"
    - "/home/{{ real_user }}/.bash_logout"
    - "/home/{{ real_user }}/.bash_profile"
    - "/home/{{ real_user }}/.bashrc"
    - "/home/{{ real_user }}/.profile"

- name: Run `stow .` from .dotfiles root.
  become: false
  ansible.builtin.command: stow .
  args:
    chdir: "/home/{{ real_user }}/.dotfiles"

- name: Clone tmux plugins.
  become: false
  ansible.builtin.git:
    repo: "https://github.com/tmux-plugins/tpm"
    dest: "/home/{{ real_user }}/.config/tmux/plugins/tpm"
    version: main
    update: no

- name: Install tmux plugins.
  become: false
  ansible.builtin.command: /"home/{{ real_user }}/.config/tmux/plugins/tpm/bin/install_plugins"
