= Fedora Installation Guide

These installation instructions are for using the Fedora sway spin and overlaying hyprland on it.

. Install from the USB drive
. Reboot the system and log in under your user account.
. Activate wifi from the network manager.
. Run `sudo vi /etc/dnf/dnf.conf` (or `sudoedit /etc/dnf/dnf.conf` if EDITOR environment variable is set)
and edit to include the following:
+
[source,ini]
----
[main]
fastestmirror = True
keepcache = True
defaultyes = True
skip_unavailable = True
max_parallel_downloads = 10
install_weak_deps = False
----
. Upgrade all packages and reboot again.
+
[source,shell]
----
sudo dnf upgrade --refresh
reboot
----
. Set up git permissions.
+
[source,shell]
----
sudo dnf install gh -y
gh auth login
----

. Clone the dotfiles repo.
+
[source,shell]
----
mkdir ~/.dotfiles
gh repo clone JanCoe/dotfiles ~/.dotfiles
----

. Go to https://rpmfusion.org/Configuration:
.. Enable access to free and nonfree under Configuration
.. Install additional codecs under Howto/Multimedia
.. Run 'sudo dnf update @core'. This installs the core packages that are conditional on rpmfusion being enabled.
.. sudo dnf group install multimedia
.. Activate OpenH264 with
+
[source,shell]
----
sudo dnf config-manager setopt fedora-cisco-openh264.enabled=1
----
. Install all the packages.
+
[source,shell]
----
./install-fedora
----

. Create symlinks of the dotfiles.
Check that the .stow-local-ignore file is correct (has to be done before running stow).
+
[source,shell]
----
cd ~/.dotfiles
stow .
----
Make sure there is no .bash_profile (because .profile would not be read if there is).

. Install Nordic gtk theme.
+
[source,shell]
----
gh repo clone EliverLara/Nordic ~/.themes/Nordic
----

. Install the kew music player, following the instructions on https://github.com/ravachol/kew, and using
the 'install-kew' script.

. Install i3lock-fancy (X11 only).
+
[source,shell]
----
mkdir -p ~/Apps/i3lock-fancy
gh repo clone meskarune/i3lock-fancy ~/Apps/i3lock-fancy
cd ~/Apps/i3lock-fancy
sudo make install
make clean
----

. Set it up so that `dunst` runs under X11 and `mako` under Wayland if both are installed:
+
[source,shell]
----
systemctl --user daemon-reexec
systemctl --user daemon-reload
systemctl --user enable --now mako.service
systemctl --user enable --now dunst.service
----

. Add the following line to `/etc/pam.d/lightdm` to ensure LightDM uses PAM with systemd support (only for X11):
+
[source]
----
session optional pam_systemd.so
----

. To show background on login screen if using lightdm:
.. Copy background to `/usr/share/backgrounds`
.. Edit `/etc/lightdm/lightdm-gtk-greeter.conf` in `[greeter]` section to use background file as background

. Enable a Nord theme:
.. Firefox: *Nord Polar Night Theme* by christos
.. Thunderbird: *Nord Hardt* by artrz (download and install)
.. Rofi: *Nord* theme from GitHub

. Setup and sync OneDrive by running:
+
[source,shell]
----
onedrive --sync
----

. Setup Proton Bridge, Thunderbird and neomutt.

. Add 1Password extension to Vivaldi. Install 1Password following instructions on their website.

. Sync with Obsidian vault:
.. Select theme under *Appearance → Themes*
.. (Installed before from github into VAULT/.obsidian/themes)
+
[source,shell]
----
git clone git@github.com:EndlessReform/obsidian-nord-muted
----
. Install JetBrains Toolbox App from their website. Use that to install PyCharm and RustRover.

. Install HyperBackupExplorer from Synology website for exploring backups.

. Set up Vivaldi as default browser

+
[source,shell]
----
xdg-settings set default-web-browser vivaldi.desktop
xdg-mime default vivaldi.desktop x-scheme-handler/http
xdg-mime default vivaldi.desktop x-scheme-handler/https
----

. Set IP addresses of machines on local network
Edit /etc/hosts as follows:
.. 127.0.0.1 localhost
.. ::1       localhost
.. 127.0.1.1 name_of_this_machine # obtained through hostname
.. ip_address name
... where ip_address is from 'hostname -I' and name is from 'hostname' on Linux systems
... where ip_address is from 'ipconfig getifaddr en0' and name is from 'hostname' on Macs 

. In future, to keep system updated:
+
[source,shell]
----
update-fedora
sudo ./remove-kernels  # from the .dotfiles/scripts directory
----
