- name: Install Rust on Fedora
  block:
    - name: Ensure rustup is installed for user
      become: true
      become_user: "{{ real_user }}"
      ansible.builtin.shell: |
        set -e
        curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
      args:
        creates: "/home/{{ real_user }}/.cargo/bin/rustup"
      environment:
        HOME: "/home/{{ real_user }}"

    - name: Install stable toolchain
      become: true
      become_user: "{{ real_user }}"
      ansible.builtin.command:
        cmd: "/home/{{ real_user }}/.cargo/bin/rustup install stable"
      environment:
        HOME: "/home/{{ real_user }}"
      args:
        creates: "/home/{{ real_user }}/.rustup/toolchains/stable-x86_64-unknown-linux-gnu"
