- name: Install Rust on macOS using Homebrew
  block:
    - name: Install rustup-init via Homebrew
      community.general.brew:
        name: rustup-init
        state: present
      become: false
      become_user: "{{ real_user }}"

    - name: Run rustup-init (non-interactive)
      ansible.builtin.command: rustup-init -y
      become: false
      become_user: "{{ real_user }}"
      environment:
        PATH: "/home/{{ real_user }}/.cargo/bin:{{ ansible_env.PATH }}"
      args:
        creates: "/home/{{ real_user }}/.cargo/bin/rustc"
  when: ansible_facts['os_family'] == "Darwin"
