- name: Install Rust on Fedora
  block:
    - name: Install Rust toolchain.
      become: true 
      ansible.builtin.dnf:
        name: rustup
        state: present

    - name: Install Rust toolchain
      ansible.builtin.command:
        cmd: rustup install stable
      become: true 
      become_user: "{{ real_user }}"
      environment:
        PATH: "/home/{{ real_user }}/.cargo/bin:{{ ansible_env.PATH }}"
      args:
        creates: "/home/{{ real_user }}/.rustup/toolchains/stable-x86_64-unknown-linux-gnu"
  when: ansible_facts['os_family'] == "RedHat"
