- name: Ensure /etc/dnf/dnf.conf exists.
  become: true
  ansible.builtin.file:
    path: /etc/dnf/dnf.conf
    state: touch
    mode: '0644'

- name: Configure DNF global options.
  become: true
  ansible.builtin.ini_file:
    path: /etc/dnf/dnf.conf
    section: main
    option: "{{ item.option }}"
    value: "{{ item.value }}"
    create: false
  loop:
    - { option: fastestmirror,         value: 'True' }
    - { option: keepcache,             value: 'True' }
    - { option: defaultyes,            value: 'True' }
    - { option: skip_unavailable,      value: 'True' }
    - { option: max_parallel_downloads, value: '10' }
    - { option: install_weak_deps,     value: 'False' }

- name: Update all packages.
  become: true
  dnf:
    name: "*"
    state: latest
    update_cache: True
  register: update_result

# - name: Reboot if packages were updated
#  reboot:
#    reboot_timeout: 600
#  when: update_result.changed

- name: Get Fedora version.
  become: true
  ansible.builtin.command: rpm -E %fedora
  register: fedora_version
  changed_when: false

- name: Add RPM Fusion Repository.
  become: true
  dnf:
    # name: "https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ fedora_version.stdout }}.noarch.rpm"
    name: "https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-42.noarch.rpm"
    disable_gpg_check: true
    state: "present"

- name: Add RPM Non-Free Fusion Repository.
  become: true
  dnf:
    name: "https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-42.noarch.rpm"
    disable_gpg_check: true
    state: present

- name: Ensure Fedora’s Cisco openh264 repo is enabled.
  become: true
  ansible.builtin.ini_file:
    path: /etc/yum.repos.d/fedora-cisco-openh264.repo
    section: fedora-cisco-openh264
    option: enabled
    value: "1"
    backup: yes

- name: Enable RPM Fusion repos.
  become: true
  dnf:
    name:
      - rpmfusion-free-release-tainted
      - rpmfusion-nonfree-release-tainted
      - libdvdcss  # for dvd support
    state: present

# This pulls in all firmware. Look for ways to slim this down. Is it needed?
#- name: Install all tainted firmware packages.
#  become: true
#  command: dnf --repo=rpmfusion-nonfree-tainted install '*-firmware' -y
