- name: Get Fedora version
  become: true
  ansible.builtin.command: rpm -E %fedora
  register: fedora_version
  changed_when: false

- name: Add RPM Fusion Repository
  become: true
  ansible.builtin.dnf:
    # name: "https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ fedora_version.stdout }}.noarch.rpm"
    name: "https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-42.noarch.rpm"
    disable_gpg_check: true
    state: "present"

- name: Add RPM Non-Free Fusion Repository
  become: true
  ansible.builtin.dnf:
    name: "https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-42.noarch.rpm"
    disable_gpg_check: true
    state: present

- name: Ensure Fedora’s Cisco openh264 repo is enabled
  become: true
  ansible.builtin.ini_file:
    path: /etc/yum.repos.d/fedora-cisco-openh264.repo
    section: fedora-cisco-openh264
    option: enabled
    value: "1"
    backup: yes

- name: Enable RPM Fusion repos
  become: true
  ansible.builtin.dnf:
    name:
      - rpmfusion-free-release-tainted
      - rpmfusion-nonfree-release-tainted
      - libdvdcss  # for dvd support
    state: present

- name: Set Openh264
  become: true
  ansible.builtin.command: dnf config-manager setopt fedora-cisco-openh264.enabled=1

- name: Ensure Flatpak is installed
  become: true 
  ansible.builtin.dnf:
    name: flatpak
    state: present

- name: Add Flathub remote if it doesn't exist (user)
  become: true
  become_user: "{{ real_user }}"
  ansible.builtin.command: flatpak remote-add --if-not-exists --user flathub https://flathub.org/repo/flathub.flatpakrepo

# This pulls in all firmware. Look for ways to slim this down. Is it needed?
#- name: Install all tainted firmware packages.
#  become: true
#  ansible.builtin.command: dnf --repo=rpmfusion-nonfree-tainted install '*-firmware' -y
